name: CI-CD
on:
  push:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
      - name: Obtendo o c√≥digo
        uses: actions/checkout@v5.0.0
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            willianmarioti/primeira-pipeline:latest
            willianmarioti/primeira-pipeline:v${{ github.run_number }}
  CD-Homolog:
    needs: [CI]
    uses: wbm01/primeira-pipeline-cicd/.github/workflows/deploy.yaml@main
    with:
      manifests: k8s/deployment.yaml
      images: willianmarioti/primeira-pipeline:v${{ github.run_number }}
      environment: homologacao
    secrets: inherit

  Teste-Ambiente:
    needs: [CD-Homolog]
    runs-on: ubuntu-latest
    environment: homologacao
    steps:
      - name: Fake Teste
        run: echo "Fake testes de ambiente ${{vars.APP_NAMESPACE}}"

  CD-Producao:
    needs: [CI]
    uses: wbm01/primeira-pipeline-cicd/.github/workflows/deploy.yaml@main
    with:
      manifests: k8s/deployment.yaml
      images: willianmarioti/primeira-pipeline:v${{ github.run_number }}
      environment: producao
    secrets: inherit